### ISSUE TITLE
create css/tailwind

### ISSUE THREAD

**Issue by crockevin** [crockevin/Game-Hub#2]
If you are working on the css/tailwind i want you to be in contact with the html team, be sure to talk about the changes you want so the other team can adjust

**Comment by nicanthoni** [comment]
Layout has been determined. Once basic HTML is available, we will begin designing the pages base look. 

Color palette has been determined, and is stored as variables in style.css file (file still needs to be linked to html).

**Comment by nicanthoni** [comment]
General layout & template for cards made.

**Comment by nicanthoni** [comment]
Updated nav bar styling, color scheme of webpage, title, and horizonal/vertical margin for card section

**Comment by nicanthoni** [comment]
Added second html file for 'free games' - to be opened via javascript by selecting free games options from main page.
