### ISSUE TITLE
JavaSript Fetch

### ISSUE THREAD

**Issue by crockevin** [crockevin/Game-Hub#4]
you will be responsible for fetching formatting the data and append it to a card, be in contact with the html and css team about to get a a html code to .innerhtml append

**Comment by nicanthoni** [comment]
@crockevin Are you able to fix the issue of 'search' not running again until page is refreshed? if you search batman, and then try to search another game before refreshing the page, nothing happens

**Comment by crockevin** [comment]
sure i can fix it, I just need to empty the child at the start of each run, also the reason it doesnt look like it changed is because the new search is below the previous search result
